src/authentication/urls.py
from django.urls import path
from . import views


app_name = 'authentication'
urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
    path('register/', views.register_view, name='register'),
    path('edit-profile/', views.edit_view, name='edit-profile'),
    path('change-password/', views.change_password_view, name='change-password')
]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls', namespace='authentication'))
]

src/authentication/models.py
from django.db import models

# Create your models here.

src/authentication/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class LoginForm(forms.Form):
    username = forms.CharField(required=True, widget=forms.TextInput)
    password = forms.CharField(required=True, widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'placeholder': field
            })

    def clean(self, *args, **kwargs):
        data = super(LoginForm, self).clean(*args, **kwargs)
        username = data.get('username')
        password = data.get('password')
        user = authenticate(username=username, password=password)
        if user is None:
            raise ValidationError('usuario o clave incorrecta')
        return data

    def save(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        return user


class SignupForm(forms.Form):
    username = forms.CharField(
        required=True, widget=forms.TextInput(attrs={"autofocus": "true"}))
    email = forms.EmailField(required=True, widget=forms.EmailInput)
    password = forms.CharField(required=True, widget=forms.PasswordInput)
    confirmation = forms.CharField(required=True, widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'placeholder': field,
            })

    def clean_username(self, *args, **kwargs):
        data = self.cleaned_data
        username = data.get('username')
        if username and User.objects.filter(username=username).exists():
            raise ValidationError('username ya en uso')
        return username

    def clean_email(self, *args, **kwargs):
        data = self.cleaned_data
        email = data.get('email')
        if email and User.objects.filter(email=email).exists():
            raise ValidationError('email ya en uso')
        return email

    def clean(self, *args, **kwargs):
        data = super(SignupForm, self).clean(*args, **kwargs)
        password = data.get('password')
        confirmation = data.get('confirmation')
        if password and confirmation and password != confirmation:
            raise ValidationError('passwords no coinciden')
        return data

    def save(self, *args, **kwargs):
        data = self.cleaned_data
        username = data.get('username')
        email = data.get('email')
        password = data.get('password')
        user = User.objects.create_user(
            username=username, email=email, password=password
        )
        return user


class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput())
    first_name = forms.CharField(required=True, widget=forms.TextInput())
    last_name = forms.CharField(required=True, widget=forms.TextInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name',
                  'last_name', 'password1', 'password2', )
    
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields.get(field).label = field.replace("_", ' ')
            self.fields.get(field).widget.attrs.update(
                {'class': 'form-control', 
                 'placeholder': self.fields.get(field).label}
            )


class ChangeProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')
        exclude = ('password',)
    
    def __init__(self, *args, **kwargs):
        super(ChangeProfileForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields.get(field).label = field.replace('_', ' ')
            self.fields.get(field).widget.attrs.update(
                {'class': 'form-control',
                'placeholder': self.fields.get(field).label}
            )
        del self.fields['password']

src/authentication/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from .forms import LoginForm, SignupForm, RegisterForm, ChangeProfileForm


def home(request):
    return render(request, 'authentication/home.html')


def login_view(request):
    if request.user.is_authenticated:
        return redirect('authentication:home')

    form = LoginForm(request.POST or None)

    if request.method == 'POST' and form.is_valid():
        user = form.save()

        if user:
            login(request, user)
            messages.info(request, 'sesion iniciada correctamente')
            return redirect('authentication:home')

    context = {'form': form}
    return render(request, 'authentication/login.html', context)


def logout_view(request):
    if not request.user.is_authenticated:
        return redirect('authentication:home')

    if request.method == 'POST':
        logout(request)
        messages.info(request, 'sesion cerrada correctamente')
        return redirect('authentication:home')


def signup_view(request):
    if request.user.is_authenticated:
        return redirect('authentication:home')

    form = SignupForm(request.POST or None)
    print(form.is_valid())

    if not form.is_valid():
        for error in form.non_field_errors():
            print(error)

    if request.method == 'POST' and form.is_valid():
        user = form.save()

        if user:
            login(request, user)
            messages.info(request, 'usuario creado exitosamente')
            return redirect('authentication:home')

    context = {'form': form}
    return render(request, 'authentication/signup.html', context)


def register_view(request):
    form = RegisterForm(request.POST or None)

    if request.method == 'POST' and form.is_valid():
        user = form.save()

        if user:
            login(request, user)
            messages.info(request, 'usuario regustrado exitosamente')
            return redirect('authentication:home')

    context = {'form': form}
    return render(request, 'authentication/register.html', context)


def edit_view(request):
    form = ChangeProfileForm(request.POST or None, instance=request.user)

    if request.method == 'POST' and form.is_valid():
        form.save()
        messages.info(request, 'datos actualizados exitosamente')
        return redirect('authentication:home')

    context = {'form': form}
    return render(request, 'authentication/edit_profile.html', context)


def change_password_view(request):
    form = PasswordChangeForm(data=request.POST or None, user=request.user)

    if request.method == 'POST' and form.is_valid():
        form.save()
        update_session_auth_hash(request, form.user)
        messages.info(request, 'contraseña cambiada')
        return redirect('authentication:home')
    
    context = {'form': form}
    return render(request, 'authentication/change_password.html', context)

src/templates/authentication/change_password.html
{% extends 'base.html' %} 

{% block content %}
<div class="row">
	<div class="col-md-6 offset-md-3 mt-3">
    <h1 class="text-center">change password</h1>

		{% if form.errors %}
			<div class="alert alert-warning alert-dismissible fade show">
				{% for field in form %} 
					{% if field.errors %} 
						{% for error in field.errors %} 
							{{ error }} 
						{% endfor %} 
					{% endif %} 
				{% endfor %} 
				
				{% if form.non_field_errors %}
					{% for error in form.non_field_errors %} 
						{{ error }} 
					{% endfor %}
				{% endif %}
				<button
        	type="button"
        	class="btn-close"
        	data-bs-dissmiss="alert"
        	aria-label="Close"
      	></button>
			</div>
    {% endif %}

		<form method="POST">
			{% csrf_token %}

			{% for field in form %}
			<div class="form-group mt-3">
				<p>{{ field.label_tag|lower }}</p>
				{{ field }}
				{% if field.help_text %}
					<div class="form-text">{{ field.help_text|safe }}</div>
				{% endif %}
			</div>
			{% endfor %}

			<div class="d-grid gap-2">
				<button type="submit" class="btn btn-primary mt-3">
					change password
				</button>
			</div>
		</form>
		
  </div>
</div>

{% endblock %}

src/templates/authentication/edit_profile.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
  <div class="col-md-6 offset-md-3 mt-3">
    <h1 class="text-center">edit profile</h1>

    {% if form.errors %}
    <div class="alert alert-warning alert-dismissible fade show">
      {% for field in form %} 
	  		{% if field.errors %}
		  		{% for error in field %} 
		  			{{ error }} 
		  		{% endfor %} 
				{% endif %} 
			{% endfor %}

			{% if form.non_field_errors %} 
				{% for error in form.non_field_errors %} 
					{{ error }} 
				{% endfor %} 
			{% endif %}
      <button
        type="button"
        class="btn-close"
        data-bs-dissmiss="alert"
        aria-label="Close"
      ></button>
    </div>
    {% endif %}

    <form method="POST">
      {% csrf_token %} 
			
			{% for field in form %}
      <div class="form-group mt-3">
        {{ field }} 
				{% if field.help_text %}
        	<div class="form-text">{{ field.help_text|safe }}</div>
        {% endif %}
      </div>
      {% endfor %}

      <div class="d-grid gap-2">
        <button type="submit" class="btn btn-primary mt-3">
          update profile
        </button>
      </div>
    </form>
		
  </div>
</div>

{% endblock %}

src/templates/authentication/home.html
{% extends 'base.html' %}

{% block content %}

{% include 'snippets/messages.html' %}
<h2 class="mt-3">Hola mundo!</h2>
<br />

{% if user.is_authenticated %}
    <p><span class="fw-bold">username:</span> {{ user.username }}</p>
    <p><span class="fw-bold">email:</span> {{ user.email }}</p>
{% endif %}

{% endblock %}

src/templates/authentication/login.html
{% extends 'base.html' %} 

{% block content %}
<div class="row">
  <div class="col-md-6 offset-md-3 mt-3">
    {% include 'snippets/messages.html' with messages=form.non_field_errors %}

    <h1 class="text-center mt-3">login</h1>
    <form method="POST">
      {% csrf_token %}

      <div class="form-group mt-3">
        <input
          type="text"
          class="form-control"
          required
          id="id_username"
          name="username"
          placeholder="username"
          autofocus="true"
        />
      </div>

      <div class="form-group mt-3">
        <input
          type="password"
          class="form-control"
          required
          id="id_password"
          name="password"
          placeholder="password"
        />
      </div>
      
      <div class="d-grid gap-2">
        <button type="submit" class="btn btn-primary mt-3">
          login
        </button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

src/templates/authentication/register.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
  <div class="col-md-6 offset-md-3 mt-3">
    <h1 class="text-center">register</h1>

    {% if form.errors %}
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {% for field in form %}
          {% if field.errors %}
            {% for error in field.errors %}
              {{ error }}
            {% endfor %}
          {% endif %}
        {% endfor %}

        {% if form.non_field_errors %}
          {% for error in form.non_field_errors %}
            {{ error }}
          {% endfor %}
        {% endif %}
        <button type="button" class="btn-close" data-bs-dimiss="alert" aria-label="Close"></button>
      </div>
    {% endif %}

    <form method="POST">
      {% csrf_token %}
      {% for field in form %}
      <div class="form-group mt-3">
        {{ field }} 
        <div class="form-text">
          {{ field.help_text }}
        </div>
      </div>
      {% endfor %}

      <div class="d-grid gap-2">
        <button type="submit" class="btn btn-primary mt-3">register</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

src/templates/authentication/signup.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
  <div class="col-md-6 offset-md-3 mt-3">
    {% include 'snippets/messages.html' with messages=form.non_field_errors %}

    <h1 class="text-center mt-3">Sign Up</h1>
    <form method="POST">
      {% csrf_token %}
      {% for field in form %}
      <div class="form-group mt-3">
        {{ field }}
        {% if field.errors %}
        <p class="text-muted">{{ field.errors }}</p>
        {% endif %}   
      </div>
      {% endfor %}

      <div class="d-grid gap-2">
        <button type="submit" class="btn btn-primary mt-3">sign up</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

src/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    {% include 'snippets/navbar.html' %}
    
    <div class="container">
    {% block content %}
    {% endblock %}
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>

src/templates/snippets/messages.html
{% if messages %}
{% for message in messages %}
<div
  class="alert alert-{% if message.tags %}{{ message.tags }}{% else %}danger{% endif %} alert-dismissible fade show mt-3"
  role="alert"
>
  {{ message }}
  <button
    type="button"
    class="btn-close"
    data-bs-dismiss="alert"
    aria-label="Close"
  ></button>
</div>
{% endfor %}
{% endif %}

src/templates/snippets/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand my-3" href="{% url 'authentication:home' %}"
      >Authentication Web App</a
    >
    <button
      class="navbar-toggler my-3"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        {% if not user.is_authenticated %}
        <li class="nav-item mx-auto px-2 py-2">
          <a
            class="btn btn-outline-success border-2 fw-bold"
            href="{% url 'authentication:login' %}"
            role="button"
            >login</a
          >
        </li>

        <li class="nav-item mx-auto px-2 py-2">
          <a
            class="btn btn-outline-success border-2 fw-bold"
            href="{% url 'authentication:signup' %}"
            role="button"
            >signup</a
          >
        </li>

        <li class="nav-item mx-auto px-2 py-2">
          <a
            class="btn btn-outline-success border-2 fw-bold"
            href="{% url 'authentication:register' %}"
            role="button"
            >register</a
          >
        </li>

        {% else %}
        <li class="nav-item mx-auto px-2 py-2">
          <a 
          class="btn btn-outline-success border-2 fw-bold"
          href="{% url 'authentication:edit-profile' %}"
          role="button"
          >edit profile</a>
        </li>

        <li class="nav-item mx-auto px-2 py-2">
          <a 
          class="btn btn-outline-success border-2 fw-bold"
          href="{% url 'authentication:change-password' %}"
          role="button"
          >change password</a>
        </li>

        <li class="nav-item mx-auto px-2 py-2">
          <form
            class="row row-cols-lg-auto g-3 align-items-center"
            method="POST"
            action="{% url 'authentication:logout' %}"
          >
            {% csrf_token %}
            <div class="col-12">
              <button
                type="submit"
                class="btn btn-outline-danger border-2 fw-bold"
              >
                logout
              </button>
            </div>
          </form>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>